/** Deutsche Ländernamen für ESPN-/englische Teamnamen */
const COUNTRY_DE: Record<string, string> = {
  Croatia: "Kroatien",
  England: "England",
  Spain: "Spanien",
  Czechia: "Tschechien",
  "Czech Republic": "Tschechien",
  Germany: "Deutschland",
  Austria: "Österreich",
  Switzerland: "Schweiz",
  France: "Frankreich",
  Italy: "Italien",
  Portugal: "Portugal",
  Netherlands: "Niederlande",
  Belgium: "Belgien",
  Denmark: "Dänemark",
  Poland: "Polen",
  Scotland: "Schottland",
  Wales: "Wales",
  "Northern Ireland": "Nordirland",
  "Republic of Ireland": "Irland",
  Ireland: "Irland",
  Serbia: "Serbien",
  Slovenia: "Slowenien",
  Slovakia: "Slowakei",
  Hungary: "Ungarn",
  Romania: "Rumänien",
  Bulgaria: "Bulgarien",
  Greece: "Griechenland",
  Turkey: "Türkei",
  Türkiye: "Türkei",
  "Bosnia and Herzegovina": "Bosnien und Herzegowina",
  "Bosnia-Herzegovina": "Bosnien und Herzegowina",
  Montenegro: "Montenegro",
  "North Macedonia": "Nordmazedonien",
  Albania: "Albanien",
  Kosovo: "Kosovo",
  Norway: "Norwegen",
  Sweden: "Schweden",
  Finland: "Finnland",
  Iceland: "Island",
  Ukraine: "Ukraine",
  Russia: "Russland",
  Georgia: "Georgien",
  Armenia: "Armenien",
  Azerbaijan: "Aserbaidschan",
  Kazakhstan: "Kasachstan",
  Israel: "Israel",
  Cyprus: "Zypern",
  Malta: "Malta",
  Luxembourg: "Luxemburg",
  Liechtenstein: "Liechtenstein",
  Andorra: "Andorra",
  "San Marino": "San Marino",
  Gibraltar: "Gibraltar",
  "Faroe Islands": "Färöer",
  Latvia: "Lettland",
  Lithuania: "Litauen",
  Estonia: "Estland",
  Moldova: "Moldau",
  Belarus: "Belarus",
  Brazil: "Brasilien",
  Argentina: "Argentinien",
  Colombia: "Kolumbien",
  Uruguay: "Uruguay",
  Mexico: "Mexiko",
  "United States": "USA",
  USA: "USA",
  Canada: "Kanada",
  Panama: "Panama",
  Ghana: "Ghana",
  Morocco: "Marokko",
  Egypt: "Ägypten",
  Japan: "Japan",
  "South Korea": "Südkorea",
  Australia: "Australien",
  "Saudi Arabia": "Saudi-Arabien",
};

export function countryDe(name: string): string {
  return COUNTRY_DE[name] ?? name;
}

/** Kurze Anzeigenamen für HNL-Clubs (TheSportsDB-Namen) */
const HNL_SHORT: Record<string, string> = {
  "Dinamo Zagreb": "Dinamo Zagreb",
  "Hajduk Split": "Hajduk Split",
  "HNK Gorica": "Gorica",
  "Slaven Belupo Koprivnica": "Slaven Belupo",
  "Lokomotiva Zagreb": "Lokomotiva",
  "Istra 1961": "Istra 1961",
  "NK Osijek": "Osijek",
  "NK Varaždin": "Varaždin",
  "HNK Rijeka": "Rijeka",
  "NK Rudeš": "Rudeš",
};

export function hnlTeam(name: string): string {
  return HNL_SHORT[name] ?? name;
}
